/*
  stress_test.c - C equivalent of stress_test.ap for LLVM IR comparison.

  IMPORTANT: This file has been generated by AI for comparison purposes.

  Mirrors the Aspect demo as closely as possible:
    - same function names and logic
    - same type widths (stdint.h)
    - explicit casts where Aspect requires them, implicit elsewhere
    - write() / puts() instead of printf() to match Aspect extern declarations
    - no stdlib number formatters (custom u64_to_str / i64_to_str, same algorithm)

  Compile to LLVM IR (unoptimised):
      clang -S -emit-llvm -O0 -o demos/stress_test_clang_O0.ll demos/stress_test.c

  Compile to LLVM IR (optimised, comparable to aspect -O2):
      clang -S -emit-llvm -O2 -o demos/stress_test_clang_O2.ll demos/stress_test.c

  Run the C binary normally:
      clang -O0 -o demos/stress_test_c demos/stress_test.c && ./demos/stress_test_c
*/

#include <stdint.h>
#include <unistd.h>   /* write() */
#include <stdio.h>    /* puts()  */

/* -- global state -------------------------------------------------------- */

int32_t g_run  = 0;
int32_t g_pass = 0;

/* Constant hex digit table */
uint8_t HEX_CHARS[16] = {48,49,50,51,52,53,54,55,56,57,65,66,67,68,69,70};

/* First eight primes */
int32_t PRIMES[8] = {2,3,5,7,11,13,17,19};

/* -- string utilities ---------------------------------------------------- */

uint64_t strlen_aspect(uint8_t *s) {
    uint64_t n = 0;
    while (s[n] != 0) n++;
    return n;
}

void print_str(uint8_t *s) {
    write(1, s, strlen_aspect(s));
}

void println_aspect(uint8_t *s) {
    uint8_t nl[2] = {10, 0};
    write(1, s, strlen_aspect(s));
    write(1, nl, 1);
}

/* -- number formatting --------------------------------------------------- */

uint8_t *u64_to_str(uint64_t v, uint8_t *buf) {
    if (v == 0) { buf[0] = 48; buf[1] = 0; return buf; }
    uint64_t i = 0;
    while (v != 0) {
        buf[i] = (uint8_t)(48 + v % 10);
        v /= 10;
        i++;
    }
    buf[i] = 0;
    uint64_t lo = 0, hi = i - 1;
    while (lo < hi) {
        uint8_t t = buf[lo]; buf[lo] = buf[hi]; buf[hi] = t;
        lo++; hi--;
    }
    return buf;
}

uint8_t *i64_to_str(int64_t v, uint8_t *buf) {
    if (v < 0) {
        buf[0] = 45;
        uint8_t tmp[22];
        u64_to_str((uint64_t)(0 - v), tmp);
        uint64_t j = 0;
        while (tmp[j] != 0) { buf[j+1] = tmp[j]; j++; }
        buf[j+1] = 0;
        return buf;
    }
    return u64_to_str((uint64_t)v, buf);
}

void print_u64(uint64_t v) {
    uint8_t buf[24];
    u64_to_str(v, buf);
    write(1, buf, strlen_aspect(buf));
}

void print_i64(int64_t v) {
    uint8_t buf[24];
    i64_to_str(v, buf);
    write(1, buf, strlen_aspect(buf));
}

/* -- test harness -------------------------------------------------------- */

void check_i64(uint8_t *name, int64_t expected, int64_t got) {
    g_run++;
    if (got == expected) {
        g_pass++;
        print_str((uint8_t *)"[PASS] ");
        println_aspect(name);
    } else {
        print_str((uint8_t *)"[FAIL] ");
        print_str(name);
        print_str((uint8_t *)"  exp=");
        print_i64(expected);
        print_str((uint8_t *)" got=");
        print_i64(got);
        println_aspect((uint8_t *)"");
    }
}

void check_u64(uint8_t *name, uint64_t expected, uint64_t got) {
    g_run++;
    if (got == expected) {
        g_pass++;
        print_str((uint8_t *)"[PASS] ");
        println_aspect(name);
    } else {
        print_str((uint8_t *)"[FAIL] ");
        print_str(name);
        print_str((uint8_t *)"  exp=");
        print_u64(expected);
        print_str((uint8_t *)" got=");
        print_u64(got);
        println_aspect((uint8_t *)"");
    }
}

/* -- math ---------------------------------------------------------------- */

uint64_t gcd(uint64_t a, uint64_t b) {
    while (b != 0) { uint64_t t = b; b = a % b; a = t; }
    return a;
}

uint64_t fib(uint32_t n) {
    if (n <= 1) return n;
    uint64_t a = 0, b = 1;
    uint32_t i = 2;
    while (i <= n) { uint64_t c = a + b; a = b; b = c; i++; }
    return b;
}

int32_t is_prime(uint64_t n) {
    if (n < 2)  return 0;
    if (n == 2) return 1;
    if (n % 2 == 0) return 0;
    uint64_t i = 3;
    while (i * i <= n) { if (n % i == 0) return 0; i += 2; }
    return 1;
}

int64_t pow_i64(int64_t base, uint32_t exp) {
    int64_t result = 1;
    while (exp > 0) { result *= base; exp--; }
    return result;
}

/* -- bit manipulation ---------------------------------------------------- */

uint32_t popcount32(uint32_t v) {
    uint32_t c = 0;
    while (v != 0) { c += v & 1; v >>= 1; }
    return c;
}

uint8_t bit_reverse8(uint8_t v) {
    uint32_t r = 0, vv = v, i = 0;
    while (i < 8) { r <<= 1; r |= vv & 1; vv >>= 1; i++; }
    return (uint8_t)r;
}

uint32_t ctz32(uint32_t v) {
    if (v == 0) return 32;
    uint32_t c = 0;
    while ((v & 1) == 0) { v >>= 1; c++; }
    return c;
}

/* -- array utilities ----------------------------------------------------- */

int64_t sum_i32(int32_t *arr, int32_t n) {
    int64_t total = 0;
    int32_t i = 0;
    while (i < n) { total += arr[i]; i++; }
    return total;
}

void sort_asc(int32_t *arr, int32_t n) {
    int32_t i = 1;
    while (i < n) {
        int32_t key = arr[i], j = i - 1;
        while (j >= 0) {
            if (arr[j] <= key) break;
            arr[j+1] = arr[j]; j--;
        }
        arr[j+1] = key; i++;
    }
}

int32_t linear_search(int32_t *arr, int32_t n, int32_t target) {
    int32_t i = 0;
    while (i < n) { if (arr[i] == target) return i; i++; }
    return -1;
}

/* -- string operations --------------------------------------------------- */

int32_t strcmp_aspect(uint8_t *a, uint8_t *b) {
    while (*a == *b && *a != 0) { a++; b++; }
    return (int32_t)*a - (int32_t)*b;
}

void strcpy_aspect(uint8_t *dst, uint8_t *src) {
    while (*src != 0) { *dst = *src; dst++; src++; }
    *dst = 0;
}

/* -- main ---------------------------------------------------------------- */

int main(void) {
    puts("=== Aspect Stress Test ===");
    puts("");

    /* -- Section 1: control flow ---------------------------------------- */
    puts("--- Control flow ---");

    int32_t v = 15, branch = 0;
    if (v < 10)       branch = 1;
    else if (v == 15) branch = 2;
    else              branch = 3;
    check_i64((uint8_t *)"if/elif/else", 2, branch);

    int64_t for_sum = 0;
    for (int32_t k = 1; k <= 100; k++) for_sum += k;
    check_i64((uint8_t *)"for sum 1..100", 5050, for_sum);

    int32_t evens = 0, w = 0;
    while (w < 20) {
        w++;
        if (w % 2 != 0) continue;
        evens += w;
    }
    check_i64((uint8_t *)"while+continue even sum", 110, evens);

    int32_t brk_sum = 0;
    for (int32_t m = 1; m <= 100; m++) {
        brk_sum += m;
        if (brk_sum > 30) break;
    }
    check_i64((uint8_t *)"for+break stops at 36", 36, brk_sum);

    /* -- Section 2: compound assignment ---------------------------------- */
    puts("");
    puts("--- Compound assignment ---");

    uint32_t b = 0xFF;
    b &= 0x0F; b |= 0x30; b ^= 0x05;
    b <<= 1;   b >>= 1;
    b %= 50;   b += 2;    b -= 2;
    b *= 3;    b /= 3;
    check_i64((uint8_t *)"compound ops (all)", 8, b);

    /* -- Section 3: math ------------------------------------------------- */
    puts("");
    puts("--- Math ---");

    check_u64((uint8_t *)"gcd(48,18)=6",    6,    gcd(48, 18));
    check_u64((uint8_t *)"gcd(100,75)=25",  25,   gcd(100, 75));
    check_u64((uint8_t *)"gcd(7,13)=1",     1,    gcd(7, 13));
    check_u64((uint8_t *)"fib(0)=0",        0,    fib(0));
    check_u64((uint8_t *)"fib(10)=55",      55,   fib(10));
    check_u64((uint8_t *)"fib(20)=6765",    6765, fib(20));
    check_i64((uint8_t *)"is_prime(1)=0",   0,    is_prime(1));
    check_i64((uint8_t *)"is_prime(2)=1",   1,    is_prime(2));
    check_i64((uint8_t *)"is_prime(97)=1",  1,    is_prime(97));
    check_i64((uint8_t *)"is_prime(100)=0", 0,    is_prime(100));
    check_i64((uint8_t *)"pow(2,10)=1024",  1024, pow_i64(2, 10));
    check_i64((uint8_t *)"pow(3,5)=243",    243,  pow_i64(3, 5));

    /* -- Section 4: bit manipulation ------------------------------------- */
    puts("");
    puts("--- Bit manipulation ---");

    check_u64((uint8_t *)"popcount(0xFF)=8",       8, popcount32(0xFF));
    check_u64((uint8_t *)"popcount(0b10110101)=5", 5, popcount32(0xB5));
    check_u64((uint8_t *)"popcount(0)=0",          0, popcount32(0));
    check_i64((uint8_t *)"bit_rev8(0x01)=0x80", 0x80, bit_reverse8(1));
    check_i64((uint8_t *)"bit_rev8(0xF0)=0x0F", 0x0F, bit_reverse8(0xF0));
    check_i64((uint8_t *)"bit_rev8(0xAA)=0x55", 0x55, bit_reverse8(0xAA));
    check_u64((uint8_t *)"ctz32(8)=3",   3, ctz32(8));
    check_u64((uint8_t *)"ctz32(12)=2",  2, ctz32(12));
    check_u64((uint8_t *)"ctz32(1)=0",   0, ctz32(1));

    uint64_t flags = 0b11001010;
    check_i64((uint8_t *)"flags & 0xF0 = 0xC0", 0xC0, flags & 0xF0);
    check_i64((uint8_t *)"flags | 0x0F = 0xCF", 0xCF, flags | 0x0F);
    check_i64((uint8_t *)"flags ^ 0xFF = 0x35", 0x35, flags ^ 0xFF);
    check_i64((uint8_t *)"1 << 7 = 128",        128,  1 << 7);
    check_i64((uint8_t *)"200 >> 3 = 25",        25,  200 >> 3);

    /* -- Section 5: arrays ----------------------------------------------- */
    puts("");
    puts("--- Arrays ---");

    int32_t fibs[6] = {0, 1, 1, 2, 3, 5};
    check_i64((uint8_t *)"const list init sum=12", 12, sum_i32(fibs, 6));

    int32_t base_val = 7;
    int32_t rt[4] = {base_val, base_val*2, base_val*3, base_val*4};
    check_i64((uint8_t *)"runtime list init sum=70", 70, sum_i32(rt, 4));

    int32_t partial[5] = {10, 20};
    check_i64((uint8_t *)"partial list init sum=30", 30, sum_i32(partial, 5));

    int32_t empty[4] = {0};
    check_i64((uint8_t *)"empty list init sum=0", 0, sum_i32(empty, 4));

    check_i64((uint8_t *)"PRIMES[0]=2",  2,  PRIMES[0]);
    check_i64((uint8_t *)"PRIMES[4]=11", 11, PRIMES[4]);
    check_i64((uint8_t *)"PRIMES[7]=19", 19, PRIMES[7]);
    check_i64((uint8_t *)"HEX_CHARS[10]='A'=65", 65, HEX_CHARS[10]);

    int32_t dyn_n = 6;
    int32_t dyn[6];
    for (int32_t di = 0; di < dyn_n; di++) dyn[di] = di + 1;
    check_i64((uint8_t *)"dynamic alloc sum=21", 21, sum_i32(dyn, dyn_n));

    int32_t tosort[8] = {5, 3, 8, 1, 9, 2, 7, 4};
    sort_asc(tosort, 8);
    check_i64((uint8_t *)"sort[0]=1", 1, tosort[0]);
    check_i64((uint8_t *)"sort[4]=5", 5, tosort[4]);
    check_i64((uint8_t *)"sort[7]=9", 9, tosort[7]);

    check_i64((uint8_t *)"search(5)=4",   4,  linear_search(tosort, 8, 5));
    check_i64((uint8_t *)"search(99)=-1", -1, linear_search(tosort, 8, 99));

    /* -- Section 6: pointers --------------------------------------------- */
    puts("");
    puts("--- Pointers ---");

    int32_t val = 77;
    int32_t *ptr = &val;
    *ptr = *ptr + 23;
    check_i64((uint8_t *)"pointer write+read=100", 100, val);

    uint8_t greeting[5] = {72, 101, 108, 108, 111};
    uint8_t *gp = greeting;
    uint64_t sum8 = 0;
    for (uint32_t gi = 0; gi < 5; gi++) sum8 += gp[gi];
    check_u64((uint8_t *)"u8* walk 'Hello' sum=500", 500, sum8);

    uint8_t src_buf[32], dst_buf[32];
    strcpy_aspect(src_buf, (uint8_t *)"StressTest");
    strcpy_aspect(dst_buf, src_buf);
    check_i64((uint8_t *)"strcpy round-trip", 0, strcmp_aspect(dst_buf, (uint8_t *)"StressTest"));

    /* -- Section 7: implicit widening ------------------------------------ */
    puts("");
    puts("--- Implicit widening ---");

    uint8_t  n8  = 200;
    uint32_t n32 = n8;
    int64_t  n64 = n32;
    check_i64((uint8_t *)"u8(200)->u32->i64", 200, n64);

    int32_t neg32 = -75;
    int64_t neg64 = neg32;
    check_i64((uint8_t *)"i32(-75)->i64", -75, neg64);

    int32_t small = 12;
    check_u64((uint8_t *)"i32 arg->u64 param gcd", 3, gcd((uint64_t)small, 9));

    check_i64((uint8_t *)"i32 result->i64 param", 1, is_prime(7));

    /* -- Section 8: floating point --------------------------------------- */
    puts("");
    puts("--- Float ---");

    double pi   = 3.14159265358979;
    double r    = 6.0;
    double area = pi * r * r;
    check_i64((uint8_t *)"pi*6^2 > 113.0", 1, area > 113.0);
    check_i64((uint8_t *)"pi*6^2 < 114.0", 1, area < 114.0);

    double xf  = 9.75;
    int64_t xi = (int64_t)xf;
    check_i64((uint8_t *)"f64 9.75 trunc->9", 9, xi);

    int32_t iv = 42;
    double  fv = (double)iv;
    int64_t bk = (int64_t)(fv * 2.0);
    check_i64((uint8_t *)"i32->f64->*2->i64=84", 84, bk);

    double acc = 0.0;
    for (int32_t fi = 0; fi < 10; fi++) acc += 0.1;
    check_i64((uint8_t *)"f64 0.1*10 > 0.99", 1, acc > 0.99);
    check_i64((uint8_t *)"f64 0.1*10 < 1.01", 1, acc < 1.01);

    /* -- Section 9: string operations ------------------------------------ */
    puts("");
    puts("--- Strings ---");

    check_i64((uint8_t *)"strcmp equal=0",   0, strcmp_aspect((uint8_t *)"hello", (uint8_t *)"hello"));
    check_i64((uint8_t *)"strcmp abc<abd<0", 1, strcmp_aspect((uint8_t *)"abc", (uint8_t *)"abd") < 0);
    check_i64((uint8_t *)"strcmp z>a>0",     1, strcmp_aspect((uint8_t *)"z", (uint8_t *)"a") > 0);
    check_u64((uint8_t *)"strlen('hello')=5", 5, strlen_aspect((uint8_t *)"hello"));
    check_u64((uint8_t *)"strlen('')=0",      0, strlen_aspect((uint8_t *)""));

    uint8_t word[8] = {65, 115, 112, 101, 99, 116, 0, 0};
    check_u64((uint8_t *)"array-built strlen=6", 6, strlen_aspect(word));
    check_i64((uint8_t *)"array-built strcmp",   0, strcmp_aspect(word, (uint8_t *)"Aspect"));

    /* -- Section 10: scope & shadowing ----------------------------------- */
    puts("");
    puts("--- Scope & shadowing ---");

    int32_t outer = 10;
    {
        int32_t outer = 20;
        outer += 5;
        check_i64((uint8_t *)"inner outer=25", 25, outer);
    }
    check_i64((uint8_t *)"outer restored=10", 10, outer);

    int32_t loop_escape = 0;
    for (int32_t li = 0; li < 5; li++) loop_escape += li;
    check_i64((uint8_t *)"for-init scope sum=10", 10, loop_escape);

    /* -- Result ---------------------------------------------------------- */
    puts("");
    print_str((uint8_t *)"Tests run: ");    print_i64(g_run);    puts("");
    print_str((uint8_t *)"Tests passed: "); print_i64(g_pass);   puts("");

    if (g_run == g_pass) puts("All tests PASSED.");
    else                 puts("SOME TESTS FAILED.");

    return g_pass;
}
